server:
  port: 9090
spring:
  application:
    name: universal-loa-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/x9x9x9x9/universal-loa-config-server
          username: x9x9x9x9
          password: lims0301